### ISSUE TITLE
Mixed Content in the Minimage README on the Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [d-kusk/minimage#37]
Hello @d-kusk and Happy New Year!

I recently [reviewed](https://github.com/gohugoio/hugoThemes/issues/532) the deploy log of the Hugo Themes website and it seems in [line 3](https://github.com/d-kusk/minimage/blame/master/README.md#L3) of your theme's README you have entered the following insecure `URL` to an external image: `http://img.shields.io/badge/license-MIT-blue.svg?style=flat` 

This image is throwing a [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) browser warning on the Hugo website since it is served under `HTTPS`.

Can you please change the above insecure img `URL` to `https://img.shields.io/badge/license-MIT-blue.svg?style=flat` so that the warning is fixed?

Once you do this please let me know.

Thanks

**Comment by dsk52** [comment]
Hello @onedrawingperday  and Happy New Year!

Thank you for me contact.
I tried changing the URL, but is this OK?

Also, should I comment on [this Issue](https://github.com/gohugoio/hugoThemes/issues/532) when this is over?

**Comment by onedrawingperday** [comment]
@d-kusk Thank you for the fix. The change will be shown the next time that Hugo Themes are updated (usually happens about once a week). Also no need to comment in the other issue.

Thanks!
