### ISSUE TITLE
The font may go wrong when a page contains multiple languages such as Chinese, English and Japanese.

### ISSUE THREAD

**Issue by hu-yan** [d-kusk/minimage#42]
Please add these fonts for multi-language support.
**css/application.css Line 24**
`font-family:"Helvetica Neue",Helvetica,Arial,"Microsoft Yahei","Hiragino Sans GB","Heiti SC","WenQuanYi Micro Hei", sans-serif`

**Comment by dsk52** [comment]
Hi, @hu-yan . Thank you for making Issue!

We can not verify the support of the language, so we have no plan to respond. sorry.

If you want to change it, a mechanism to override Hugo's template file may be helpful.
https://gohugo.io/templates/base/#base-template-lookup-order

**Comment by hu-yan** [comment]
All right 😊, I have  had changed the font settings in the CSS file of this theme and now it just works fine on my site. Thanks for your work on this theme.
