### ISSUE TITLE
mathjax commonHMTL output is messed by `.c-post__body *+*{margin-top:0.9rem} `

### ISSUE THREAD

**Issue by codetrainee** [d-kusk/minimage#53]
The default value is `0.9 rem` but it caused the messy mathjax `commonHTML` output as below:

```
.c-post__body *+* {
  margin-top: 0.9rem;
}
```
![image](https://user-images.githubusercontent.com/8357863/58372141-c4623500-7f5c-11e9-987a-84d79668d4b7.png)

```
.c-post__body *+* {
  margin-top: 0%;
}
```
![image](https://user-images.githubusercontent.com/8357863/58372124-8d8c1f00-7f5c-11e9-8f6e-3f216f00ab49.png)

**Comment by dsk52** [comment]
Hi, @codetrainee  thank's for telling me.

I did not expect to put formulas at all.
Also thank you for finding a solution.

However, I think that it is a rare case to put and use formulas.
In addition, if it makes it 0%, sentences will stick. I do not like this very much. 😥

If you want to use that CSS specification, add it to the CSS file (``css/application.css``) or create a new CSS file and write it.

**Comment by codetrainee** [comment]
Thanks, 

I've found a workaround that only applies to mathjax. The default value still works on other parts.

```
.math.inline *+*, .math.display *+* {
  margin-top: 0
}
```
