### ISSUE TITLE
GitHub token is pushed as well

### ISSUE THREAD

**Issue by plxty** [d-kusk/minimage#64]
I found the token in [travis configuration](https://github.com/d-kusk/minimage/blob/develop/.travis.yml#L24) file. Isn't that dangerous? 🤔 I guess you might need a new token.

**Comment by dsk52** [comment]
Hi, @kerneliz 
It's probably fine because it's the code after travis encrypt.
But I was worried about it, so I regenerated it and deleted it from the file.
